fix: handle backend errors in pool page
balancer/frontend-v3 pull request #1031
Opened 2024-08-29 15:09 UTC by agualis

Before this fix any backend error in a pool query would crash the app and send an error to sentry.

<img width="683" alt="Screenshot 2024-08-29 at 17 07 10" src="https://github.com/user-attachments/assets/bd5ec309-0c57-46ac-a459-033733b3bf9e">

After this fix: 
- We detect invalid pool id error. 
- We capture other errors in sentry
- We show an alert instead of crashing the app:

<img width="1294" alt="error" src="https://github.com/user-attachments/assets/235aba81-ec65-41a7-ae7f-a25a272875e9">

2024-08-30 07:57 UTC, agualis commented on app/(app)/pools/[chain]/[variant]/[id]/layout.tsx
> +    if (error?.message === 'Pool with id does not exist') {
As far as I know we are not receiving any error code here.

2024-08-30 08:28 UTC, garethfuller commented on app/(app)/pools/[chain]/[variant]/[id]/layout.tsx
> +    if (error?.message === 'Pool with id does not exist') {
We should get a 404 from the request response. We should use that as Anastas points out. This doesn't provide an example, but if we could try and follow Next.js patterns for error handling, that would be great: https://nextjs.org/docs/app/building-your-application/routing/error-handling

2024-08-30 10:05 UTC, garethfuller commented on app/(app)/pools/[chain]/[variant]/[id]/layout.tsx
> +    if (error?.message === 'Pool with id does not exist') {
Yeah agree we need to get something that at least handles the error in the meantime.

2024-08-30 10:38 UTC, garethfuller requested changes

2024-08-30 10:38 UTC, garethfuller commented on app/(app)/pools/[chain]/[variant]/[id]/layout.tsx
> +      const error = `Pool with id not found in ${chain} (${id})`
```suggestion
      const error = `Pool not found on ${chain}, ID (${id})`
```

2024-08-30 10:38 UTC, garethfuller commented on app/(app)/pools/[chain]/[variant]/[id]/layout.tsx
> +          content="Our API data provider appears to be having issues..."
```suggestion
          content="Failed to fetch pool"
```

2024-09-04 13:19 UTC, garethfuller reviewed
@agualis I'm struggling to get this to work how I wanted with Error boundaries. It works in dev, but in production it blocks you from rendering error messages that are thrown in server components for security reasons, which makes sense.

I need to move on to something else for now, maybe you could take another look. Maybe you were right to start with by just rendering an error message on the RSC.

2024-09-13 14:41 UTC, merged