fix: transaction state 'resets'
balancer/frontend-v3 pull request #1092
Opened 2024-09-16 14:10 UTC by groninge01

2024-09-17 10:56 UTC, groninge01 commented on lib/modules/swap/modal/SwapModal.tsx
> +  const { stopPolling } = useTokens()
Renamed

2024-09-18 09:22 UTC, garethfuller requested changes

2024-09-18 09:22 UTC, garethfuller commented on lib/modules/tokens/TokensProvider.tsx
> +  } = useQuery(GetTokenPricesDocument, {
Lets not export the polling interval as well since it's internal context. We can do this instead:
```suggestion
    startPolling,
    stopPolling,
  } = useQuery(GetTokenPricesDocument, {

const startTokenPricePolling = () => startPolling(pollInterval)
const stopTokenPricePolling = () => stopPolling(pollInterval)
```
And export those.

2024-09-18 11:30 UTC, groninge01 commented on lib/modules/tokens/TokensProvider.tsx
> +  } = useQuery(GetTokenPricesDocument, {
Updated this.

2024-09-19 14:22 UTC, garethfuller approved these changes

2024-09-19 14:22 UTC, merged