add ng-apimock for dev mocking
balancer/frontend-v3 pull request #769
Opened 2024-07-11 05:46 UTC by groninge01

- add backend mocking

2024-07-24 10:12 UTC, garethfuller commented
@groninge01 closing for now, feel free to reopen if you want to keep working on it.

2024-08-07 06:43 UTC, agualis requested changes
Small changes requested.

Looks goods to me if you find it useful. As I said, I would like to try to have the same testing feature with MSW to remove this `ng-apiMock` dependency but we can take a look at that in the future.

2024-08-07 06:43 UTC, agualis commented on package.json
> +    "cors": "^2.8.5",
If this is only required by `ng-apimock` feature we should move it to `devDependencies`

2024-08-07 06:43 UTC, agualis commented on test/ng-apimock/mocks/data/getPool.json
> +{
Better rename to `getPool.mock.json` to match other similar json mock files ([getPool.mock.json](https://github.com/balancer/frontend-v3/pull/769/files#diff-67659822893fc2a6cc737fcad54bf178f91454a43e04e409be71581e984a7aa9))

2024-08-07 06:43 UTC, agualis commented on test/ng-apimock/mocks/data/getPoolSnapshots.json
> +{
Rename to `getPoolSnapshots.mock.json`

2024-08-08 08:48 UTC, groninge01 commented on test/ng-apimock/mocks/data/getPool.json
> +{
this is the (response) data for the `getPool` mock

2024-08-08 08:48 UTC, groninge01 commented on test/ng-apimock/mocks/data/getPoolSnapshots.json
> +{
this is the (response) data for the `getPoolSnapshots` mock

2024-08-08 08:55 UTC, groninge01 commented
> Small changes requested.
> 
> Looks goods to me if you find it useful. As I said, I would like to try to have the same testing feature with MSW to remove this `ng-apiMock` dependency but we can take a look at that in the future.

Let's wait for that then. If I need mocks before that's ready I'll just checkout this branch.

2024-08-08 08:55 UTC, closed without merging