fix: improve swap error handling when sdk buildCall throws
balancer/frontend-v3 pull request #832
Opened 2024-07-19 12:26 UTC by agualis

We have an unsolved bug where sdk priceImpact and simulation work but `buildCall` is throwing.

This fix improves the captured error and displays the error to the user.

2024-07-19 12:28 UTC, agualis commented on lib/modules/swap/useSwapStep.tsx
> +            <ManagedSendTransactionButton
Note that we are hiding the button here. We could probably show it disabled but this is an edge-case so I think it is ok for now.

2024-07-22 13:28 UTC, garethfuller requested changes

2024-07-22 13:28 UTC, garethfuller commented on lib/modules/swap/useSwapStep.tsx
> +            <ManagedSendTransactionButton
I'm against adding this to the step logic. It should be included as part of the modal component.

2024-07-24 07:29 UTC, agualis commented on lib/modules/swap/useSwapStep.tsx
> +            <ManagedSendTransactionButton
The problem is that we build `useBuildSwapQuery` within this file so we don't have access to the error in the modal component. We should think about a little refactor then.

2024-07-26 07:37 UTC, agualis commented on lib/modules/swap/useSwapStep.tsx
> +            <ManagedSendTransactionButton
@garethfuller I undid that change so that we can merge the rest of the code. 

And we can take a decision about how to display this edge-case error later.

2024-07-29 08:21 UTC, garethfuller approved these changes

2024-07-29 08:21 UTC, merged