fix: show alert when the pool requires proportional adds but has no liquidity
balancer/frontend-v3 pull request #868
Opened 2024-07-25 14:40 UTC by agualis

**Before**: 
Opening the addLiquidity url of a pool that requires proportional (gyro or CoW) but does no have liquidity (`totalShares===0`) leads to different errors. 

**After:** 
We show an alert: 

![Screenshot 2024-07-25 at 16 40 09](https://github.com/user-attachments/assets/f2b6e97e-4f0d-4ede-824d-c19499bd1288)

2024-07-25 19:48 UTC, garethfuller requested changes
I would change this to:
1. Show the form with disabled input regardless
2. Make this more generic, we don't support any init joins, so if any pool type doesn't have any shares we should show this message.

2024-07-26 07:22 UTC, agualis commented
> I would change this to:
> 
> 1. Show the form with disabled input regardless
> 2. Make this more generic, we don't support any init joins, so if any pool type doesn't have any shares we should show this message.

I updated the code but what happens if there was an init join but then all liquidity was removed? In non proportional pools, it should be possible to add though the UI, right?

2024-07-26 08:02 UTC, garethfuller commented
> > I would change this to:
> > 
> > 1. Show the form with disabled input regardless
> > 2. Make this more generic, we don't support any init joins, so if any pool type doesn't have any shares we should show this message.
> 
> I updated the code but what happens if there was an init join but then all liquidity was removed? In non proportional pools, it should be possible to add though the UI, right?

@agualis I'd say this is an edge case that we're better off blocking to start with and see if it causes any problems. If someone has removed all liquidity then the pool is probably not viable.

2024-07-26 08:04 UTC, garethfuller approved these changes

2024-07-26 08:04 UTC, merged