Fix/receipt logs
balancer/frontend-v3 pull request #960
Opened 2024-08-12 17:17 UTC by agualis

It uses the logs from the transaction receipts instead of the previous explicit queries. 

This should be more efficient (less queries) and more reliable as it avoids quering the `blockHash`.

2024-08-14 11:23 UTC, garethfuller reviewed
Just tested this in a CoW pool and it worked. But there is this delay between the modal transitioning to the success state and displaying the receipt information. Can we easily delay the transition to the success state in cases where we're waiting for the parsed receipt data?

2024-08-14 16:55 UTC, agualis commented
> Just tested this in a CoW pool and it worked. But there is this delay between the modal transitioning to the success state and displaying the receipt information. Can we easily delay the transition to the success state in cases where we're waiting for the parsed receipt data?

Created another PR on top of this one: 
https://github.com/balancer/frontend-v3/pull/970

Please check the description.

2024-08-19 14:40 UTC, garethfuller requested changes
There is a long delay between the success state (you hear the success noise, see the animation etc) and the quote appearing. This can't be the case, it's really bad UX. If we are waiting for a quote then the success state should wait until the logs are ready.

2024-08-20 14:35 UTC, garethfuller approved these changes

2024-08-20 14:35 UTC, merged