add beets features
balancer/frontend-v3 pull request #963
Opened 2024-08-13 12:09 UTC by groninge01

2024-08-14 08:39 UTC, agualis requested changes

2024-08-14 08:39 UTC, agualis commented on app/manifest.ts
> +import { getProjectConfig } from '@/lib/config/getProjectConfig'
We already had `manifest.ts` but I had delete it and use a mainifest.json instead to make it work with Safe App.
(We are acutally using the other manifes.json inside `/pools` https://github.com/balancer/frontend-v3/blob/main/public/pools/manifest.json#L16-L17

We will need to find a workaround if we want both balancer and beets working as Safe Apps.

2024-08-14 08:39 UTC, agualis commented on public/pools/manifest.ts
> +import { getProjectConfig } from '@/lib/config/getProjectConfig'
This breaks the Safe App compatibility (see comment above).

2024-08-14 09:00 UTC, garethfuller commented on lib/config/config.types.ts
> +  features: { [key in Features]: boolean }
I'm not sure about this schema. It allows Beets features to be accidentally turned on within the Balancer app or vice versa. These features should be defined by the project config but I realise that makes it difficult if they are network-specific as well.

2024-08-14 11:58 UTC, groninge01 commented on lib/config/config.types.ts
> +  features: { [key in Features]: boolean }
as they are indeed network specific i added them here

i can add `isBeets` to them to make it more explicit? (just like i already did with `vebal && isBalancer` which is needed for beets on optimism)

2024-08-14 12:00 UTC, groninge01 commented on lib/config/app.config.ts
> +  const defaultNetwork = networksByChainId[process.env.NEXT_PUBLIC_DEFAULT_CHAIN_ID || 250]
i added a default network in the project config but then i ran into an initialization error there as `isProd` isn't available yet (comes from this file which is still being initialized)

2024-08-14 12:01 UTC, groninge01 commented on app/(app)/mabeets/page.beets.tsx
i add `.beets` for consistency & clarity, i will look into grouping the beets features

2024-08-14 12:08 UTC, groninge01 commented on app/(app)/mabeets/layout.tsx
> +}
this is fixed

2024-08-15 08:53 UTC, groninge01 commented on app/manifest.ts
> +import { getProjectConfig } from '@/lib/config/getProjectConfig'
Do we actually need a manifest here?

2024-08-15 08:54 UTC, groninge01 commented on public/pools/manifest.ts
> +import { getProjectConfig } from '@/lib/config/getProjectConfig'
Reverted this as Safe is not up for a change rn :(

2024-08-15 09:30 UTC, groninge01 commented on app/(app)/mabeets/page.beets.tsx
i grouped the beets routes

2024-09-03 08:03 UTC, garethfuller commented on lib/shared/components/navs/Navbar.tsx
> +  const { appLinks, beetsLinks, AppLink } = useNav()
Should feature/project specific links maybe be part of the config?

2024-09-03 08:52 UTC, groninge01 commented on lib/modules/web3/ChainConfig.tsx
> +  [GqlChain.Fantom]: customFantom,
Good catch. I have removed them.

2024-09-03 08:59 UTC, groninge01 commented on app/(marketing)/page.tsx
> +    import(`@/lib/shared/components/marketing/Home.${projectId}`).then(mod => mod.HomeContent)
That's because `dynamic` lazy-loads the main content. I didn't want to do

```
{ isBal && <HomeContentBal }
{ isBeets && <HomeContentBeets }
```

`'use client'` isn't needed so I'll remove that and then I'll look a bit more into `dynamic`.

2024-09-03 11:11 UTC, groninge01 commented on lib/config/config.types.ts
> +  poolname = 'poolname',
Split into project options for now.

2024-09-03 13:38 UTC, groninge01 commented on lib/shared/components/navs/Navbar.tsx
> +  const { appLinks, beetsLinks, AppLink } = useNav()
Moved some links to the project configs.

2024-09-03 14:57 UTC, groninge01 commented on app/manifest.ts
> +import { getProjectConfig } from '@/lib/config/getProjectConfig'
We could put just one manifest.json in the root if safe would use it's start_url prop. But unfortunately they don't...
So I think we remove it here and just have the one in /pools. Is that ok?

When the time comes for beets to be a safe app @agualis has a way to copy the correct json to the correct location.

2024-09-13 11:24 UTC, groninge01 commented on app/manifest.ts
> +import { getProjectConfig } from '@/lib/config/getProjectConfig'
Reverted this too for now.

2024-09-23 11:16 UTC, closed without merging

2024-09-23 11:16 UTC, groninge01 commented
keep remote branch for now